### ISSUE TITLE
Not properly marked as non-free software

### ISSUE THREAD

**Issue by legoktm** [flathub/com.scoutshonour.dtipbijays#2]
in GNOME Software, this app shows up as free software, but it uses the NC variant of Creative Commons, making it non-free. This should be properly marked, as I know other non-free applications show up as "Proprietary".

![screenshot from 2018-07-27 19-28-33](https://user-images.githubusercontent.com/81392/43352117-752a67f4-91d3-11e8-9356-678c0274890a.png)

**Comment by TingPing** [comment]
The license is correct, so this is a discussion entirely for GNOME Software about if it should be called free or not.
