### ISSUE TITLE
Update to runtime 21.08

### ISSUE THREAD

**Issue by MateusRodCosta** [flathub/com.scoutshonour.dtipbijays#6]
Should have been updated a while ago

**Comment by MateusRodCosta** [comment]
Runtime fdo 21.08 seems to not ship with FreeType2, and that breaks the build of one the dependencies.
Until that is fixed, either by using a new shared module (no module for FreeType is available at the moment) or somebody manually builds it on the manifest, let's stay on 20.08.

**Comment by hfiguiere** [comment]
it does ship with freetype2. Just that that version removed freetype-config after over 10 years of "it's deprecated"

**Comment by MateusRodCosta** [comment]
Oh, then I will investigate at some point in the future, most likely close to when 20.08 gets EOLd.

**Comment by orowith2os** [comment]
we're on 22.08 now, I'm looking into updating to that.

**Comment by orowith2os** [comment]
Looks like the new target is 23.08. @bbhtt seems to be interested in that :P

**Comment by bbhtt** [comment]
Testing appreciated. I'm not familiar with this game or the renpy engine.
